# Configuration parameters for feature selection and model training

data_processing_parameters:
  feature_bin_count: 10
  time_shift_ms: 200
  sample_rate: 16000
  clip_duration_ms: 1000
  window_size_ms: 40.0
  window_stride_ms: 20.0
  # Added
  feature_extraction_method: 'mfcc' # can be 'raw' / 'mfcc' / ...

training_parameters:
  data_dir: 'dataset/speech_commands_v0.02'
  data_url: 'https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz'
  target_words: 'yes,no,up,down,left,right,on,off,stop,go'  # GSCv2 - 12 words
  epochs: 40
  batch_size: 128
  silence_percentage: 10.0
  unknown_percentage: 10.0
  validation_percentage: 10.0
  testing_percentage: 10.0
  background_frequency: 0.8
  background_volume: 0.2
  # Model Training parameters
  criterion: 'CrossEnt'
  initial_lr: 0.001
  optimizer: 'Adam'
  scheduler: 'LambdaLR'

model_parameters:
  pt: 'models/wav2vec/wav2vec_small.pt'


# Selecting 35 words, take below
# target_words: 'yes,no,up,down,left,right,on,off,stop,go,backward,bed,bird,cat,dog,eight,five,follow,forward,four,
# happy,house,learn,marvin,nine,one,seven,sheila,six,three,tree,two,visual,wow,zero,'  # GSCv2 - 35 words