name: kwsenv
channels:
  - defaults
dependencies:
  - ca-certificates=2022.3.29
  - certifi=2020.6.20=pyhd3eb1b0_3
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.2
  - python=3.6.13
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.38.2
  - tk=8.6.11
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.9
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - dataclasses==0.8
    - decorator==5.1.1
    - einops==0.4.1
    - idna==3.3
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - librosa==0.9.1
    - llvmlite==0.36.0
    - matplotlib==3.3.4
    - numba==0.53.1
    - numpy==1.19.5
    - packaging==21.3
    - pandas==1.1.5
    - pillow==8.4.0
    - pooch==1.6.0
    - pthflops==0.4.1
    - pycparser==2.21
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - requests==2.27.1
    - resampy==0.2.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - six==1.16.0
    - soundfile==0.10.3.post1
    - threadpoolctl==3.1.0
    - torch==1.4.0
    - torchaudio==0.4.0
    - torchsummary==1.5.1
    - typing-extensions==4.1.1
    - urllib3==1.26.9